//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 03:54:38 PM AST 
//


package com.gramazski.xmlparsing.entity.attribute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoolerAppointment.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CoolerAppointment">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SystemUnit"/>
 *     &lt;enumeration value="CPU"/>
 *     &lt;enumeration value="HardDrive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CoolerAppointment")
@XmlEnum
public enum CoolerAppointment {

    @XmlEnumValue("SystemUnit")
    SYSTEM_UNIT("SystemUnit"),
    CPU("CPU"),
    @XmlEnumValue("HardDrive")
    HARD_DRIVE("HardDrive");
    private final String value;

    CoolerAppointment(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CoolerAppointment fromValue(String v) {
        for (CoolerAppointment c: CoolerAppointment.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
