//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 03:54:38 PM AST 
//


package com.gramazski.xmlparsing.entity.attribute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrystalCodeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CrystalCodeName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Broadwell"/>
 *     &lt;enumeration value="Richwell"/>
 *     &lt;enumeration value="Haswell"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CrystalCodeName")
@XmlEnum
public enum CrystalCodeName {

    @XmlEnumValue("Broadwell")
    BROADWELL("Broadwell"),
    @XmlEnumValue("Richwell")
    RICHWELL("Richwell"),
    @XmlEnumValue("Haswell")
    HASWELL("Haswell");
    private final String value;

    CrystalCodeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CrystalCodeName fromValue(String v) {
        for (CrystalCodeName c: CrystalCodeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
