//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 03:54:38 PM AST 
//


package com.gramazski.xmlparsing.entity.attribute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Socket.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Socket">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LGA1150"/>
 *     &lt;enumeration value="FM2"/>
 *     &lt;enumeration value="LGA2011-3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Socket")
@XmlEnum
public enum Socket {

    @XmlEnumValue("LGA1150")
    LGA_1150("LGA1150"),
    @XmlEnumValue("FM2")
    FM_2("FM2"),
    @XmlEnumValue("LGA2011-3")
    LGA_2011_3("LGA2011-3");
    private final String value;

    Socket(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Socket fromValue(String v) {
        for (Socket c: Socket.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
