//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.14 at 03:25:16 PM AST 
//


package com.gramazski.xmlparsing.entity;

import com.gramazski.xmlparsing.entity.attribute.CPUComplexName;
import com.gramazski.xmlparsing.entity.attribute.Origin;
import com.gramazski.xmlparsing.entity.hierarchy.CPU;
import com.gramazski.xmlparsing.entity.hierarchy.Cooler;
import com.gramazski.xmlparsing.entity.hierarchy.Device;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gramazski.xmlparsing.entity.devices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cooler_QNAME = new QName("http://www.gramazski.com/xmlparsing/entity/devices", "cooler");
    private final static QName _Cpu_QNAME = new QName("http://www.gramazski.com/xmlparsing/entity/devices", "cpu");
    private final static QName _Device_QNAME = new QName("http://www.gramazski.com/xmlparsing/entity/devices", "device");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gramazski.xmlparsing.entity.devices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Devices }
     * 
     */
    public Devices createDevices() {
        return new Devices();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Cooler }
     * 
     */
    public Cooler createCooler() {
        return new Cooler();
    }

    /**
     * Create an instance of {@link CPU }
     * 
     */
    public CPU createCPU() {
        return new CPU();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link CPUComplexName }
     * 
     */
    public CPUComplexName createCPUComplexName() {
        return new CPUComplexName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cooler }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gramazski.com/xmlparsing/entity/devices", name = "cooler", substitutionHeadNamespace = "http://www.gramazski.com/xmlparsing/entity/devices", substitutionHeadName = "device")
    public JAXBElement<Cooler> createCooler(Cooler value) {
        return new JAXBElement<Cooler>(_Cooler_QNAME, Cooler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CPU }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gramazski.com/xmlparsing/entity/devices", name = "cpu", substitutionHeadNamespace = "http://www.gramazski.com/xmlparsing/entity/devices", substitutionHeadName = "device")
    public JAXBElement<CPU> createCpu(CPU value) {
        return new JAXBElement<CPU>(_Cpu_QNAME, CPU.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Device }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gramazski.com/xmlparsing/entity/devices", name = "device")
    public JAXBElement<Device> createDevice(Device value) {
        return new JAXBElement<Device>(_Device_QNAME, Device.class, null, value);
    }

}
