//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 03:54:38 PM AST 
//


package com.gramazski.xmlparsing.entity.hierarchy;

import com.gramazski.xmlparsing.entity.attribute.CoolerAppointment;
import com.gramazski.xmlparsing.entity.attribute.CoolerBrand;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for Cooler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cooler">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/devices}Device">
 *       &lt;sequence>
 *         &lt;element name="noiseLimit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="rotationSpeed" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="brand" type="{http://www.example.com/devices}CoolerBrand"/>
 *       &lt;/sequence>
 *       &lt;attribute name="appointment" use="required" type="{http://www.example.com/devices}CoolerAppointment" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cooler", propOrder = {
    "noiseLimit",
    "rotationSpeed",
    "brand"
})
public class Cooler extends Device {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger noiseLimit;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger rotationSpeed;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CoolerBrand brand;
    @XmlAttribute(name = "appointment", required = true)
    protected CoolerAppointment appointment;

    /**
     * Gets the value of the noiseLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoiseLimit() {
        return noiseLimit;
    }

    /**
     * Sets the value of the noiseLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoiseLimit(BigInteger value) {
        this.noiseLimit = value;
    }

    /**
     * Gets the value of the rotationSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRotationSpeed() {
        return rotationSpeed;
    }

    /**
     * Sets the value of the rotationSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRotationSpeed(BigInteger value) {
        this.rotationSpeed = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link CoolerBrand }
     *     
     */
    public CoolerBrand getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoolerBrand }
     *     
     */
    public void setBrand(CoolerBrand value) {
        this.brand = value;
    }

    /**
     * Gets the value of the appointment property.
     * 
     * @return
     *     possible object is
     *     {@link CoolerAppointment }
     *     
     */
    public CoolerAppointment getAppointment() {
        return appointment;
    }

    /**
     * Sets the value of the appointment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoolerAppointment }
     *     
     */
    public void setAppointment(CoolerAppointment value) {
        this.appointment = value;
    }

}
