//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 03:54:38 PM AST 
//


package com.gramazski.xmlparsing.entity.hierarchy;

import com.gramazski.xmlparsing.entity.attribute.CPUComplexName;
import com.gramazski.xmlparsing.entity.attribute.CrystalCodeName;
import com.gramazski.xmlparsing.entity.attribute.Socket;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for CPU complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CPU">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/devices}Device">
 *       &lt;sequence>
 *         &lt;element name="crystal" type="{http://www.example.com/devices}CrystalCodeName"/>
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="coresNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="complexName" type="{http://www.example.com/devices}CPUComplexName"/>
 *       &lt;/sequence>
 *       &lt;attribute name="socket" use="required" type="{http://www.example.com/devices}Socket" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CPU", propOrder = {
    "crystal",
    "frequency",
    "coresNumber",
    "complexName"
})
public class CPU extends Device {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CrystalCodeName crystal;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger frequency;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger coresNumber;
    @XmlElement(required = true)
    protected CPUComplexName complexName;
    @XmlAttribute(name = "socket", required = true)
    protected Socket socket;

    /**
     * Gets the value of the crystal property.
     * 
     * @return
     *     possible object is
     *     {@link CrystalCodeName }
     *     
     */
    public CrystalCodeName getCrystal() {
        return crystal;
    }

    /**
     * Sets the value of the crystal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrystalCodeName }
     *     
     */
    public void setCrystal(CrystalCodeName value) {
        this.crystal = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFrequency(BigInteger value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the coresNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCoresNumber() {
        return coresNumber;
    }

    /**
     * Sets the value of the coresNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCoresNumber(BigInteger value) {
        this.coresNumber = value;
    }

    /**
     * Gets the value of the complexName property.
     * 
     * @return
     *     possible object is
     *     {@link CPUComplexName }
     *     
     */
    public CPUComplexName getComplexName() {
        return complexName;
    }

    /**
     * Sets the value of the complexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPUComplexName }
     *     
     */
    public void setComplexName(CPUComplexName value) {
        this.complexName = value;
    }

    /**
     * Gets the value of the socket property.
     * 
     * @return
     *     possible object is
     *     {@link Socket }
     *     
     */
    public Socket getSocket() {
        return socket;
    }

    /**
     * Sets the value of the socket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Socket }
     *     
     */
    public void setSocket(Socket value) {
        this.socket = value;
    }

}
